#
# blacklist.conf
# ==============
#
# In this file the blacklist for the automatic fixes search is
# configured. There are two ways to blacklist potential fixes:
#
#	1) Put a source code path on one line in this file. If a patch
#	   touches only source code paths that are blacklisted in this
#	   file, it will be automatically blacklisted too.
#
#	2) Put a full git commit-id on one line in this file. The
#	   commit-id needs to be a 40 character-long hex string.
#
# As noted above, only one path or commit-id per line is allowed.
# Everything behind a '#' character is considered a comment and ignored.
#
# This file is parsed by the git-suse tool.

# Blacklisted Paths
# -----------------
MAINTAINERS		# We don't care about upstream MAINTAINERS file

# Blacklisted Commits
# -------------------
a99d34e5ecb9a8f2212ee5a01140313bb115f9be # does not apply
fd2ac113a5dcb0ff14a66f8b798a88b8da26fe7e # conflict
1b9f7aafa44f5ce852c00509104d10fd9eb0f402 # conflict
836efd35c472d89c838d7b17ef339ddb3286ffc5 # conflict
0039ac8305064e455f04d412ec3896c4fe41d04f # only docu
