#! /bin/bash

#
# Check if all files referenced by series.conf are in the CVS.
#

. ${0%/*}/wd-functions.sh

if ! $using_git; then
	exit 0
fi

export LANG=C

patches="$(scripts/guards --list < series.conf | sort -u)"

if [ "$1" = "--committed" ]; then
    # check if patches and kabi files are committed
    added="$(git ls-tree -r --name-only HEAD | grep '^patches\..*/' |
	     sort -u)"
    not_in_git="$(join -v1 <(echo "$patches") <(echo "$added"))
		$(git ls-files -d -o -m --exclude-standard kabi/ | sort -u)"
else
    # only if the patches are added
    added="$(git ls-files --cached | grep '^patches\..*/' | sort -u)"
    not_in_git="$(join -v1 <(echo "$patches") <(echo "$added"))"
fi

if [ -n "$not_in_git" ]; then
    for patch in $not_in_git; do
	if [ -e "$patch" ]; then
	    echo "Not in GIT: $patch" >&2
	    status=1
	else
	    echo "Missing: $patch" >&2
	    status=1
	fi
    done
    exit $status
fi
