#!/bin/bash

#############################################################################
# Copyright (c) 2026 SUSE LLC
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.   See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, contact SUSE LLC.
#
# To contact SUSE about this file by physical or electronic mail,
# you may find current contact information at www.suse.com
#############################################################################
# Install git merge driver attributes to $GIT_DIR/info/attributes

cdup=$(git rev-parse --show-cdup) || exit
cd "${cdup:-./}" || exit
GIT_DIR=$(git rev-parse --git-common-dir) || exit
SCRIPTS_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

check_attributes()
{
    local attr_file="$GIT_DIR/info/attributes"
    test -f "$attr_file" && \
        grep -qs "series.conf.*merge=git-sort" "$attr_file" && \
        grep -qs "blacklist.conf.*merge=union" "$attr_file" && \
        grep -qs "patches.suse/\*\.patch.*merge=references" "$attr_file"
}

install_attributes()
{
    local attr_file="$GIT_DIR/info/attributes"
    local info_dir="$GIT_DIR/info"

    mkdir -p "$info_dir"

    # Create or update attributes file
    if ! test -f "$attr_file"; then
        cat > "$attr_file" <<'EOF'
# Custom merge drivers for kernel-source
series.conf	merge=git-sort
blacklist.conf	merge=union
patches.suse/*.patch	merge=references
EOF
    else
        # Check and add missing entries
        if ! grep -qs "series.conf.*merge=git-sort" "$attr_file"; then
            echo "series.conf	merge=git-sort" >> "$attr_file"
        fi
        if ! grep -qs "blacklist.conf.*merge=union" "$attr_file"; then
            echo "blacklist.conf	merge=union" >> "$attr_file"
        fi
        if ! grep -qs "patches.suse/\*\.patch.*merge=references" "$attr_file"; then
            echo "patches.suse/*.patch	merge=references" >> "$attr_file"
        fi
    fi
}

uninstall_attributes()
{
    local attr_file="$GIT_DIR/info/attributes"

    if ! test -f "$attr_file"; then
        echo "No attributes file found at $attr_file"
        return 0
    fi

    # Remove kernel-source merge driver entries
    sed -i '/^series\.conf[[:space:]].*merge=git-sort/d' "$attr_file"
    sed -i '/^blacklist\.conf[[:space:]].*merge=union/d' "$attr_file"
    sed -i '/^patches\.suse\/\*\.patch[[:space:]].*merge=references/d' "$attr_file"
    # Also remove the comment line if it exists and is now orphaned
    sed -i '/^# Custom merge drivers for kernel-source$/d' "$attr_file"

    # Remove file if it's now empty or only contains whitespace/comments
    if ! grep -q '^[^#[:space:]]' "$attr_file" 2>/dev/null; then
        rm -f "$attr_file"
        echo "Removed empty attributes file."
    fi
}

case "$1" in
--check)
    check_attributes
    exit
    ;;
--uninstall)
    echo "Uninstalling git merge driver attributes."
    uninstall_attributes
    ;;
"")
    echo "Installing git merge driver attributes."
    install_attributes
    ;;
*)
    echo "Usage: $0 [--check|--uninstall]" >&2
    exit 1
    ;;
esac

# vim: sw=4 : et
